[package]
edition = "2021"
name = "kazahane"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binrw = "0.8.4"
bytes = "1.1.0"
tokio = {version = "1.17.0", features = ["full"]}
axum = { version = "0.5.3", features = ["ws", "headers"] }

[dev-dependencies]
hyper = "0.14.18"
tower = "0.4.12"