[package]
edition = "2021"
name = "kazahane"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binrw = "0.8.4"
bytes = "1.1.0"
tokio = {version = "1.17.0", features = ["full"]}
tokio-stream = "0.1"
tokio-util = {version = "0.7.1", features = ["full"]}
